### ISSUE TITLE
Feature request: run leela-zero from a remote server

### ISSUE THREAD

**Issue by roy7** [CamWagner/lizzie#92]
With Sabaki you can run LZ remotely by giving it an ssh command for the go engine as mentioned here:

https://www.reddit.com/r/baduk/comments/6ofhha/how_to_run_leela_on_the_cloud/dkhej3g/

But since leelaz.exe is hard coded into the lizzie jar, that's not really an option here. I wonder how hard it'd be to support (command line option, config file, whatever) a way to run an arbitrary program + params like Sabaki so we might be able to run Lizzie on one machine but LZ itself on a different one?

**Comment by featurecat** [comment]
so is the idea to run arbitrary bots on lizzie, with custom program arguments and a gtp console?

**Comment by roy7** [comment]
I guess it could expand to that, but my primary interest was to try replacing leelaz.exe with say ssh.exe and being able to spawn a leelaz on a remote server that is much faster than my desktop.

**Comment by featurecat** [comment]
Oh I see. that's a really useful feature (for a subset of users). It's not super high on my priority list but I'd accept it as a pr. otherwise I will make it by 0.5 or 0.6

**Comment by dfannius** [comment]
I just changed leelaz to be a shell script that runs Leela Zero via ssh on a different machine. This is a piece of cake on macOS or Unix but might be more annoying on Windows. I agree that it would be nice to be able to do this with a configuration parameter rather than slyly renaming the supposed leelaz executable.

**Comment by dwt** [comment]
Just having a shell script called leelaz that then calls out via SSH is also what I do. For me it looks something like this (to be run in Sabaki). I'm still investigating how to get this to work with Lizzie.

```sh
#!/usr/bin/env bash

networks_dir=/home/dwt/leela-zero/archived-weights/weights
host=fast.nvidia.card.de
newest_network=$(ssh -n $host ls -tr $networks_dir/|tail -n 1)

leela_zero=/home/dwt/leela-zero/repo/src/leelaz
exec ssh $host $leela_zero --gtp --weights $networks_dir/$newest_network $*
```

I think it would be great to document this approach for Linux / Mac users that have access to a beefy server.

**Comment by dwt** [comment]
This is what I'm currently using to run leelaz via ssh on another machine, please feel free to adapt it for the documentation. Some caveats: as I can't use the local weights file, I am currently ignoring all arguments, and replicate them by hand.

```sh
% cat leelaz 
#!/usr/bin/env bash

lizzie_options="--lagbuffer 0"

networks_dir=/home/dwt/leela-zero/archived-weights/weights
host=avd
newest_network=$(ssh -n $host ls -tr $networks_dir/|tail -n 1)

leela_zero=/home/dwt/leela-zero/repo-experiments/src/leelaz
exec ssh $host $leela_zero --gtp --weights $networks_dir/$newest_network $lizzie_options
```

**Comment by featurecat** [comment]
wow thanks for posting these, I can use them ☺️ I'll add this thread to the documentation so others can find this more easily

**Comment by featurecat** [comment]
Since the latest version of Leelaz.java uses a more robust process builder algorithm, I think I might just allow the configuration file to read something like:

    leelaz_command: "./leelaz -g -b 0 w $network -t $threads"

which would obviously be replaceable with whatever command you like. But not recommended to modify for most users. Maybe we should add inline comments to the configuration file.

**Comment by dwt** [comment]
Commented configuration files are always a good idea. 

I would also like to recommend to use the long command line switches as they are much easier to read and look up fo users.

**Comment by featurecat** [comment]
Maybe... I think we will actually just have an in-app options menu to set things via the UI, instead of commandline switches. Unless you have a strong argument for them.

**Comment by dwt** [comment]
Oh I was just referring to the command line switches that lizzie uses to call leelaz. So instead of `./leelaz -g -b 0 w $network -t $threads` I would recommend to generate something more along the line of `./leelaz --gtp --lagbuffer 0 --weights $path_to_network --threads $number_of_threads`.

**Comment by featurecat** [comment]
Oh, I see what you mean. Good point!

**Comment by OlivierBlanvillain** [comment]
@dwt Would you have time to submit a submit document this in a PR? I think it might get more visibility if was an paragraph in the README as opposed to an issue.

**Comment by YiDianRen** [comment]
The following is my "engine-command" string in the config.txt:
_"gcloud compute --project %gcp-project ssh --zone %gcp-zone %gcp-instance --command %gcp-command"_
However, Lizzie06 output an error message:_Did not find LeelaZero, update config.txt or download from LeelaZero homepage_
Could someone help me with this problem?
@roy7 @featurecat @dwt @OlivierBlanvillain

**Comment by featurecat** [comment]
The code responsible for that error message is found here: 

`    // Check if engine is present
    File startfolder = new File(config.optString("engine-start-location", "."));
    File lef = startfolder.toPath().resolve(new File(commands.get(0)).toPath()).toFile();
    System.out.println(lef.getPath());
    if (!lef.exists()) {
      JOptionPane.showMessageDialog(
          null,
          resourceBundle.getString("LizzieFrame.display.leelaz-missing"),
          "Lizzie - Error!",
          JOptionPane.ERROR_MESSAGE);
      throw new IOException("engine not present");
    }

    // Check if network file is present
    File wf = startfolder.toPath().resolve(new File(currentWeightFile).toPath()).toFile();
    if (!wf.exists()) {
      JOptionPane.showMessageDialog(
          null, resourceBundle.getString("LizzieFrame.display.network-missing"));
      throw new IOException("network-file not present");
}`

This code searches for Leela Zero in your local directory, and tries to output a helpful error message in case you are missing any files. Obviously for a remote command, this is counterproductive. Try including a leelaz executable and a weight file named according to the config, in your local directory. That will keep this code happy, I think, and let you run the actual command that you want to run. Let me know if this works, and I'm sorry that the solution is not obvious.

**Comment by YiDianRen** [comment]
@featurecat Thanks to your reply. 
Lizzie can run the local Leelazero without any problem.
The following command, which runs LeelaZero on the Google Cloud Platform, can be executed correctly in the Terminal of OS:
`gcloud compute --project %gcp-project ssh --zone %gcp-zone %gcp-instance --command %gcp-command`
So, how can Lizzie connect the remote LeelaZero by the above command?

**Comment by siulkilulki** [comment]
With Lizzie 0.6, @dwt method for running lizzie with leela-zero through ssh doesn't work. I tried some values for 'engine-start-location' and 'engine-command' and I have manged to get past the 'check if engine is present' code, but then I got NullPointerException on engine start.
`Exception in thread "main" java.lang.NullPointerException
 at java.base/java.io.File.<init>(File.java:276)
 at featurecat.lizzie.analysis.Leelaz.startEngine(Leelaz.java:142)
 at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:107)`

Did anybody figure out how to do it with Lizzie 0.6? Lizzie 0.5 works just fine.

**Comment by featurecat** [comment]
Have you tried following my advice? I'm not sure if the OP tried it - include a DUMMY Leelaz executable and a dummy weight file, in your directory, as if you were going to use them. These won't actually be executed, only the engine command will be executed. I think this should work, please try it and let me know.

**Comment by dfannius** [comment]
I have been using the method that @siulkilulki and @featurecat recommend in their latest comments and it works fine for me. Ideally Lizzie would be aware of the fact that it is running Leela Zero remotely and that there doesn't need to be a weights file locally. Maybe I will try to add such a feature.

**Comment by InHill** [comment]
Lizzie is now running after 'gcloud' login successfully. Thanks to your great help, @featurecat @siulkilulki @dfannius.
There is another problem the computing in Lizzie interrupts frequently while using the remote engine. To be curious, the computing recovers automatically after serveral minutes of pause. Meanwhile, the network connection  works well. Does anyone else encounter the same problem as me? How to solve it?

**Comment by der0pa** [comment]
I apologize if this is not posted in the optimal location. 
i am trying to connect Lizzie to Leela-zero running on Google Cloud.

i have leela-zero running as described here:
https://docs.google.com/document/d/1P_c-RbeLKjv1umc4rMEgvIVrUUZSeY0WAtYHjaxjD64/edit
it's journalctl command is outputting properly.

explicitly what should the Lizzie config.txt contain on the client?
tia
